version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./scripts/development/postgres/create-table-test-schema.sql:/docker-entrypoint-initdb.d/create-tables.sql
      - ./scripts/development/postgres/spring-course-test-schema.sql:/docker-entrypoint-initdb.d/insert.sql
    environment:
      POSTGRES_USER: "equivalencia_disciplina"
      POSTGRES_PASSWORD: "equivalencia_disciplina"
      POSTGRES_DB: "equivalencia_disciplina"
    ports:
      - "5432:5432"

networks:
  mysql-compose-network:
    driver: bridge