spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/discipline_equivalence
    username: root
    password: discipline_equivalence
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
          format_sql: false

server:
  port: 8080
