spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/equivalencia_disciplina
    username: root
    password: equivalencia_disciplina
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
          format_sql: false
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

server:
  port: 8080
