spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/equivalencia_disciplina
    username: equivalencia_disciplina
    password: equivalencia_disciplina
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
          format_sql: false
          dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

server:
  port: 8080
