info:
  app:
    name: @project.artifactId@
    version: @project.version@
server:
  servlet:
    context-path: /@project.artifactId@
spring:
  application:
    name: @project.artifactId@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: application.log

logging:
  file:
    name: application.log
  logback:
    rollingpolicy:
      max-file-size: 500MB

default:
  sender: matheus.costa@tutanota.com
  recipient: matheus.costa@tutanota.com


discipline-equivalence:
  email-notification:
    cron-schedule: 0 0/1 * 1/1 * ?
  open-ai-analysis:
    cron-schedule: 0 0/1 * 1/1 * ?
  discipline-modification:
    cron-schedule: 0 0/1 * 1/1 * ?

jwt:
  secret: ${SECRET_JWT}
  expiration: 86400000

openai:
  model: ${OPEN_AI_MODEL}
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${API_KEY}